vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        life:
            uri_prefix: /images/life
            upload_destination: '%kernel.project_dir%/public/images/life'
